package com.mycompany.test1;
// Generated 03-Mar-2014 20:24:34 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Auta generated by hbm2java
 */
@Entity
@Table(name="auta"
    ,catalog="test"
)
public class Auta  implements java.io.Serializable {


     private int id;
     private String farba;
     private String znacka;

    public Auta() {
    }

    public Auta(int id, String farba, String znacka) {
       this.id = id;
       this.farba = farba;
       this.znacka = znacka;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="farba", nullable=false, length=20)
    public String getFarba() {
        return this.farba;
    }
    
    public void setFarba(String farba) {
        this.farba = farba;
    }

    
    @Column(name="znacka", nullable=false, length=15)
    public String getZnacka() {
        return this.znacka;
    }
    
    public void setZnacka(String znacka) {
        this.znacka = znacka;
    }




}


