package com.mycompany.test1;
// Generated 03-Mar-2014 20:24:34 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Thanhvien generated by hbm2java
 */
@Entity
@Table(name="thanhvien"
    ,catalog="test"
)
public class Thanhvien  implements java.io.Serializable {


     private int id;
     private String nick;
     private String heslo;

    public Thanhvien() {
    }

    public Thanhvien(int id, String nick, String heslo) {
       this.id = id;
       this.nick = nick;
       this.heslo = heslo;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Nick", nullable=false, length=45)
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }

    
    @Column(name="Heslo", nullable=false, length=30)
    public String getHeslo() {
        return this.heslo;
    }
    
    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }




}


